module.exports = {
  common: {
    message: "ニュース？センター",
    flowAudit1: "流量審査",
    from: "距離",
    reset1: "空をクリア",
    interceptContent: "尊敬するユーザーは、この機能にアクセスする権限がありません。管理者に連絡して、このサービスを開通してください。",
    interceptTip: "暖かいヒント",
    deviceType: "デバイス型式",
    searchDeviceTip: "最低5桁の数字または英語2つまたは中国語1つを入力してください。",
    importTips: "導入した設備は30条を超えてはいけないので注意してください。",
    searchDeviceTip1: "少なくとも5つのキーワードを入力してください。",
    searchUserTip1: "ユーザー名/ログインIDを入力してください。",
    loading: "読み込み中...",
    nodata: "データがありません",
    searchResultNum: "検索結果の個数",
    noresult: "検索結果がありません",
    searchResult: "検索結果",
    backtree: "ユーザツリー",
    Chinese: "中国語",
    English: "英語",
    baidu: "Baiduの地図",
    bing: "必ず地図に応ずる",
    gao: "高徳地図",
    all: "全部",
    notice: "注意 ",
    currentPage: "現在のページ",
    perPage: "バー/ページ",
    num: "番号付け",
    boundaryTip: "現在の入力行政区域を取得できませんでした。",
    selectUser: "ユーザを選択",
    linkman: "連絡先",
    phone: "電話",
    address: "住所",
    status: "状態",
    userName: "ユーザ名",
    deviceImei: "デバイス番号",
    createTime: "作成時間",
    updateTime: "更新日時",
    operation: "操作",
    delete: "削除",
    myCustomer: "私の取引先",
    chooseFile: "選択ファイルをクリックします",
    selectedFile: "選択済みファイル",
    download: "ダウンロード",
    open: "開く",
    submit: "送信",
    reset: "リセット",
    template: "テンプレート",
    searchUserTip: "ユーザ名/ユーザ名",
    searchDevTip: "デバイス番号/デバイス名",
    carNo: "ナンバープレート",
    simNo: "sim号",
    deviceName: "デバイス名",
    monitor: "モニタ",
    track: "跡をつける",
    detail: "詳細",
    playback: "再生する",
    search: "検索",
    search1: "クエリー",
    showUser: "表示",
    owner: "車の所有者名",
    type: "タイプ",
    export: "エクスポート",
    exportAll: "すべてをエクスポート",
    exportTip: "エクスポートデータを選択してください。",
    exportError: "エクスポート失敗！",
    refresh: "更新",
    alarmType: "アラームタイプ",
    startTime: "開始時間",
    endTime: "終了時間",
    save: "保存",
    cancel: "キャンセル",
    // addressFail: "地址解析失败",
    addressFail: "基地局の位置が取得されていません。",
    addressFail1: "WIFIホットスポットの位置が取得されていません。",
    addressFail2: "衛星位置が取得されていません。",
    containChild: "下位ユーザーを含む",
    frcTip: "まだチャージしていません。金融風コントロールモジュールを開通しました。",
    userTypeList: [
      {
        text: "サブアカウント",
      },
      {
        text: "ユーザー",
      },
      {
        text: "ディーラー",
      },
      {
        text: "賃貸しする",
      },
      {
        text: "物流",
      },
      {
        text: "4S店(OBD)",
      },
      {
        text: "補修工場",
      },
    ],
    ok: "を選択します",
    close: "閉じる",
    note: "コメント",
    backHome: "ホームページに戻ります",
    deviceList: "デバイスリスト",
    alarmTypeList: [
      {
        text: "全部",
        num: 1,
      },
      {
        text: "振動アラーム",
        num: 2,
      },
      {
        text: "停電して警察に通報する",
        num: 3,
      },
      {
        text: "低电报警",
        num: 4,
      },
      {
        text: "SOS求救",
        num: 5,
      },
      {
        text: "超速报警",
        num: 6,
      },
      {
        text: "出围栏报警",
        num: 7,
      },
      {
        text: "位移报警",
        num: 8,
      },
      {
        text: "GPS短路报警",
        num: 9,
      },
      {
        text: "GPS开路报警",
        num: 10,
      },
      {
        text: "进入盲区报警",
        num: 11,
      },
      {
        text: "离开盲区报警",
        num: 12,
      },
      {
        text: "外电低电报警",
        num: 13,
      },
      {
        text: "外电低电保护报警",
        num: 14,
      },
      {
        text: "启动报警",
        num: 15,
      },
      {
        text: "开门报警",
        num: 16,
      },
      {
        text: "关门报警",
        num: 17,
      },
      {
        text: "流量即将到期报警",
        num: 18,
      },
      {
        text: "流量到期报警",
        num: 19,
      },
      {
        text: "开关报警",
        num: 20,
      },
      {
        text: "感光报警",
        num: 21,
      },
      {
        text: "离线报警",
        num: 25,
      },
      {
        text: "急加速",
        num: 31,
      },
      {
        text: "急减速",
        num: 32,
      },
      {
        text: "急左转",
        num: 33,
      },
      {
        text: "急右转",
        num: 34,
      },
      {
        text: "弱信号报警",
        num: 28,
      },
      {
        text: "考勤打卡",
        num: 44,
      },
      {
        text: "静止报警",
        num: 45,
      },
      {
        text: "干扰屏蔽锁车",
        num: 46,
      },
      {
        text: "蓝牙断连锁车",
        num: 47,
      },
      {
        text: "通信网络信号恢复报警",
        num: 29,
      },
    ],
  },
  login: {
    cards: [
      {
        title: "iPhone版",
        text: "在Appstore搜索“多米智联”",
        icon: "icon-icode",
      },
      {
        title: "Android版",
        text: "在安卓市场搜索“多米智联”",
        icon: "icon-androidcode",
        download: "https://www.basegps.com/updateapk/domilinkV1.7.apk",
      },
      {
        title: "移动端",
        text: "扫码或点击链接使用移动端",
        icon: "icon-mobile",
        url: "https://www.basegps.com/carweb2/mobile/index.html#/",
      },
      {
        title: "微信版",
        text: "请用微信扫描关注“多米智联”",
        icon: "icon-wxcode",
      },
      {
        title: "小程序",
        text: "请用微信扫描使用“多米车联网”",
        icon: "icon-wxmincode",
      },
    ],
    login: "ログイン",
    userLogin: "ユーザーID",
    userTip: "IMEI/ユーザ名/ナンバープレート",
    pwdTip: "パスワード",
    remember: "次回は自動登録します",
    forget: "パスワードを忘れます",
    loginError: "ログインに失敗しました。ユーザ名が存在しないかパスワードが正しくないか、または期限が切れています。",
    tip: "マルチメートル智聯APP V 1.5バージョンが正式に発表されました。",
    loginBtn: "ログイン",
    loginBtn1: "ログイン中...",
    remeberPwd: "パスワードを覚えてください",
    v3version: "V3 version",
    v2version: "V2 version",
    versionTips: "v 3バージョンが流暢ではないなら、v 2バージョンを選択してください。",
    titleHead: "人と車を交換し，全世界にサービスする。",
  },
};
